name: 'Surge Teardown'
description: 'Teardown Surge.sh projects that match a regex'
inputs:
  regex:
    description: 'Regex string'
    required: true
    default: "[2-9]+ months ago"
  dryrun:
    description: 'Output Actions instead of applying them'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'